### PR TITLE
Pronouns: Reborn

### PR DESCRIPTION
**Pull request by joelMMD**
> It is terrible that the mod is called "Pronoun pizza" and that descripts "Gives the pizza a pronoun." This has not been true. All of the pizzas have had pronouns. This edition will fix these issues and restore them to just one pronoun each pizza. Many changes have been made and it  th_luckystar sorry It now changes the pronouns to pronoun. This have been reflected. No duplicates

### CODE REVIEW

**Comment by joelMMD** [comment]
PlayStation 2 - Dragon Ball Z Budokai Tenkaichi 3 - Goku
Holy fuck theres this many marios

**Comment by sneakykestrel** [comment]
how can this be good . theres no load bearing whitespace

**Comment by patmanf** [comment]
it's peam

**Comment by joelMMD** [comment]
it's so fucking over

**Pull request closed without merging**
